### ISSUE TITLE
NDK_PROJECT_PATH=null  这个错误？

### ISSUE THREAD

**Issue by fanei** [BruceWind/AESJniEncrypt#16]
Error while executing process /Users/fan/Library/Android/sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/fan/Documents/workspace1/AESJniEncrypt-master/aesjni/src/main/jni/Android.mk NDK_APPLICATION_MK=/Users/fan/Documents/workspace1/AESJniEncrypt-master/aesjni/src/main/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-15 NDK_OUT=/Users/fan/Documents/workspace1/AESJniEncrypt-master/aesjni/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/fan/Documents/workspace1/AESJniEncrypt-master/aesjni/build/intermediates/ndkBuild/debug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

**Comment by weizongwei5** [comment]
mac?  linux ?

**Comment by fanei** [comment]
对的，是mac

**Comment by weizongwei5** [comment]
你去跑 下这个脚本。 mac的shell

  
https://github.com/weizongwei5/Obfuscator-LLVM-4.0-BUILD-NDK

不行的话  提issues在这个 github。

**Comment by BruceWind** [comment]
If you don't respond long time, I will close this issue.
