### ISSUE TITLE
能否更新一下jni文件夹

### ISSUE THREAD

**Issue by Sopage** [BruceWind/AESJniEncrypt#19]
扰乱在新版ndk中怎么配置

**Comment by Sopage** [comment]
好的，我用14B扰乱编译完成了，code inject能解决我感觉就完美了

**Comment by weizongwei5** [comment]
这东西 永远不会有完美的情况，做了code inject 还会有别的hack方法，永无止境。

**Comment by Sopage** [comment]
嗯，确实，只是让漏斗更细小而已

**Comment by BruceWind** [comment]
你更新了  jni目录吗    如果更新了自测通过能否提一个 pull request给我
