### ISSUE TITLE
请问可以自定义初始向量吗

### ISSUE THREAD

**Issue by ydz00ydz** [BruceWind/AESJniEncrypt#22]
好像看到AES初始化向量相关代码被你删掉了？

**Comment by BruceWind** [comment]
目前没有向量，这个库的核心不在于算法，我的错，仓库命名不应该这么起。
重要的是代码的保护，不在于算法。 你需要做向量的话请fork之后添加。

**Comment by BruceWind** [comment]
或许你可以添加一个带向量的版本，自测一下然后给我一个pull request。

**Comment by BruceWind** [comment]
改动成本应该不高。

**Comment by ydz00ydz** [comment]
> 或许你可以添加一个带向量的版本，自测一下然后给我一个pull request。

搞不定啊大哥，昨天刚接触JNI，到处找现成的源代码，碰到需我改动的就懵逼了。

**Comment by BruceWind** [comment]
。。。。。硬着头皮上吧。。。。
这东西没有多难。

**Comment by ydz00ydz** [comment]
> 。。。。。硬着头皮上吧。。。。
> 这东西没有多难。

主要时间紧，C也写不来，就很费劲了。正硬着头皮读你代码。。。

**Comment by BruceWind** [comment]
这。。。。

**Comment by ydz00ydz** [comment]
大哥，先别走。你代码默认是ECB？支持CBC吗

**Comment by BruceWind** [comment]
大哥 代码在这里，如果你要CBC 我只能有空再去加。。。。

**Comment by BruceWind** [comment]
支持起来并不难。

**Comment by ydz00ydz** [comment]
好吧 先star着了 我再找找其他现成的 谢了
