### ISSUE TITLE
ndk-build出错

### ISSUE THREAD

**Issue by gityan** [BruceWind/AESJniEncrypt#28]
make: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/ollvm-4.0/prebuilt/darwin-x86_64/bin/clang++: Command not found

报了这个错 不知为何会用到darwin-x86_64   并没有改过配置

**Comment by BruceWind** [comment]
Did u use "cmake" do that?

**Comment by gityan** [comment]
我把Linux-x86_64里的文件copy到darwin-x86_64里了  现在报了另外一个错
ld: unknown option: --sysroot=/Users/xxx/Library/Android/sdk/ndk-bundle/platforms/android-17/arch-arm
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by BruceWind** [comment]
look this> https://github.com/BruceWind/AESJniEncrypt/issues/17
might cause of your ndk version.

**Comment by BruceWind** [comment]
maybe u can change the line [L23](https://github.com/BruceWind/AESJniEncrypt/blob/master/aesjni/build.gradle#L23),to remove 'x86-x64'

**Comment by gityan** [comment]
L23 这里原本就只保留了armeabi-v7a
我把ndk改为r13了，之前的问题的确没有了。
不过还是报了新的错误，可能是某处语法的问题，有待研究。
Error: r13 not allowed here -- `sub.w sp,r0,#24'

**Comment by BruceWind** [comment]
sorry, my computer has been using the 13 version of ndk. there should be a problem with the high version. 
if I want to change to a higher version I need to go through some tests. moreover, there is still something disturbing by the code, and the scrambler needs to be regenerated.




Thank you for using this library.

**Comment by gityan** [comment]
嗯嗯  最终我用了ndk r15  可以正常build  多谢你的指导
