### ISSUE TITLE
AES解密，某些字符串尾部出现乱码

### ISSUE THREAD

**Issue by pengzee** [BruceWind/AESJniEncrypt#29]
字符串内容

**Comment by pengzee** [comment]
![image](https://user-images.githubusercontent.com/19775909/60593370-28d2a880-9dd5-11e9-812b-dbfbeb6cd0b6.png)

**Comment by BruceWind** [comment]
你的秘文是什么 key是什么我来测试一下

**Comment by BruceWind** [comment]
是不是原文过短？小于16个字符？

**Comment by pengzee** [comment]
您有邮箱吗？我私发给你，加密的是公司的一些接口API地址

**Comment by BruceWind** [comment]
sorry im late, lookthis > [after 1 hour expire](https://pastebin.com/PyGzwbVs)

**Comment by BruceWind** [comment]
pls check the function > [aes.c#L578](https://github.com/BruceWind/AESJniEncrypt/blob/master/aesjni/src/main/cpp/aes.c#L578)

**Comment by BruceWind** [comment]
Hello ?  Is everything ok?

**Comment by pengzee** [comment]
不行，先close了
