### ISSUE TITLE
我发现加密“Hello World!\n你好，世界！”时，多次执行，加密出来的结果不一样，这个问题该怎么改？

### ISSUE THREAD

**Issue by LTP4399** [BruceWind/AESJniEncrypt#30]
我在实际项目中把这个集成进来之后，用了一个两行的字符串“Hello World!\n你好，世界！”进行测试，发现多次执行，输出的密文不一致，大概有三种，其中一种可以在网站在线解密中用我设置的密文解密出来，还有两种不行，但是加密之后执行解密方法，这3个都可以解密出原文，不知道问题出在哪。
密文那里我将我的密文转Base64之后前面加了个随机字母（看初始代码，key指针跳过了第一个字符），长度也改了，多次尝试都会出现这个现象

**Comment by LTP4399** [comment]
还有key的Base64后面多加了两个字符，计算长度的时候怎么去掉呢？

**Comment by BruceWind** [comment]
你修改了key？

**Comment by BruceWind** [comment]
如果你不知道怎么修改key的 可以看下getkey() 函数的变更记录。

**Comment by LTP4399** [comment]
看起来就像是key转Base64的char *，然后前面加N个字母（指针赋值的时候+N跳过前面的N的字符），不过Base64后面的等号去掉感觉没多大意义，我看到b64_decode_ex方法已经去掉了等号

**Comment by BruceWind** [comment]
给你两种方法尝试。
1.你先切换会之前我代码里的key试试。
2.如果有问题 把你的  Hello World!\n你好，世界！ 里的\n  去掉 在再试试。

**Comment by LTP4399** [comment]
大致排查出原因应该是getKey()方法出了问题，abcdef@123转Base64后是YWJjZGVmQDEyMw==，我的getKey()方法如下：
`char *getKey() {
    int n = 0;//YWJjZGVmQDEyMw==
    char s[15];
    s[n++] = 'N';
    s[n++] = 'Y';
    s[n++] = 'W';
    s[n++] = 'J';
    s[n++] = 'j';
    s[n++] = 'Z';
    s[n++] = 'G';
    s[n++] = 'V';
    s[n++] = 'm';
    s[n++] = 'Q';
    s[n++] = 'D';
    s[n++] = 'E';
    s[n++] = 'y';
    s[n++] = 'M';
    s[n++] = 'w';
    char *encode_str = s + 1;
    return b64_decode(encode_str, strlen(encode_str));
}`
但是感觉不出来是哪个地方出问题了

**Comment by BruceWind** [comment]
既然定位到了，剩下的靠你自己了。
你可以试着修改这个getkey函数 ，看下历史记录 最初我并没有getkey函数  这里只是为了隐藏key，仅此而已，这个方法你可以做很多的修改。

**Comment by BruceWind** [comment]
i need close the  issue.

**Comment by LTP4399** [comment]
大致发现一个规律，key中有@符号的时候会出现加密结果不一致的情况，只有字母和数字的时候正常

**Comment by BruceWind** [comment]
emm，这是一个精简的aes算法，不要过分纠结于算法，你可以尝试替换算法，其他的各种安全措施保留即可。

**Comment by LTP4399** [comment]
加密的问题解决了，但是解密的时候部分字符串没法解密出来，比如{"data":"data","int":1,"china":"中文"}

**Comment by BruceWind** [comment]
hello ？
是不是解密时得出的文本 被截断了？

**Comment by LTP4399** [comment]
这个我解决了，在计算填充起始下标的方法里，我传入了长度，因为每次操作16字节，只需要拿传入的长度减去最后一个byte的值就OK了，不能用strlen，因为申请的空间后面没有结尾标识符

**Comment by BruceWind** [comment]
能提个pull reqeust 给我吗？

**Comment by LTP4399** [comment]
刚试了一下，不知道怎么提交pull request,我这里大致贴出变化的部分吧！
aes.c的AES_128_ECB_PKCS5Padding_Decrypt方法int index = .....后面替换为
`int index = (int)(count * 16 - out[count * 16 -1]);
    memset(out+index, '\0', 1);
    free(inputDesBase64);
    return (char *) out;`

**Comment by BruceWind** [comment]
你可以贴这个文件给我。

**Comment by BruceWind** [comment]
pull request 步骤：
1.fork 这个仓库
2.修改本地文件 commit push
3.在github上操作 pull request
