### ISSUE TITLE
check_is_emulator如何判断是机顶盒呢

### ISSUE THREAD

**Issue by Piscen** [BruceWind/AESJniEncrypt#32]
当前代码测试发现机顶盒会被当做模拟器处理，如何判断是机顶盒呢

**Comment by BruceWind** [comment]
right, I know that. 
Im so sorry. my test occur same problem.
[look this funtion](https://github.com/BruceWind/AESJniEncrypt/blob/master/aesjni/src/main/cpp/check_emulator.c#L43), the algorithm not very good. pls check  and try remove some code.

**Comment by BruceWind** [comment]
What is the model of the TV box?  as XIAOMI?  as HUAWEI?

**Comment by BruceWind** [comment]
I want to tell you: the algorithm isn't importanly,you can remove it.

**Comment by BruceWind** [comment]
If you dont respond long time, I close the question.
