### ISSUE TITLE
请问怎么把密码1234567890abcdef处理成NMTIzNDU2Nzg5MGFiY2RlZg 求教

### ISSUE THREAD

**Issue by sy5251** [BruceWind/AESJniEncrypt#39]
"NMTIzNDU2Nzg5MGFiY2RlZg";//这里是key被做过处理存储在这里的,实际上真实的key是："1234567890abcdef"
我想问一下怎么把密码处理成NMTIzNDU2Nzg5MGFiY2RlZg ，谢谢了

**Comment by BruceWind** [comment]
Base64(0123456789abcde) 即可，注意长度16位。

**Comment by sy5251** [comment]
谢谢知道了

**Comment by BruceWind** [comment]
Ok, hope you enjoy it.
