### ISSUE TITLE
是否支持 flutter ?

### ISSUE THREAD

**Issue by 2-3-8-4-0-3-6-9-9-2** [BruceWind/AESJniEncrypt#41]
大佬的项目感觉很不错啊, 想弄到 flutter 里去, 看了下dart ffi, 把 https://dart.dev/guides/libraries/c-interop#examples 里的 hello_world 和 primitives 跑通了, 但还是不知道怎么弄到flutter里啊

https://github.com/dart-lang/samples/issues/13#issuecomment-598246232

![dart1](https://user-images.githubusercontent.com/48049456/117979483-89ce4e80-b365-11eb-8ffb-f777d3b1523e.png)
![dart2](https://user-images.githubusercontent.com/48049456/117979515-92bf2000-b365-11eb-9a60-bba491d58d24.png)

**Comment by BruceWind** [comment]
我当前有混编 libsodium啊，老哥。
该项目不面向 windows，mac。只面向android，如果你只在Android里面调，用fluttercall Java就行了，没必要那么麻烦，ios你可能需要再从头来 想办法混编libsodium。

**Comment by 2-3-8-4-0-3-6-9-9-2** [comment]
> 我当前有混编 libsodium啊，老哥。
> 该项目不面向 windows，mac。只面向android，如果你只在Android里面调，用flutter call Java就行了，没必要那么麻烦。
> 
> ios你可能需要再从头来 想办法混编libsodium。


看了一些资料，那个Obfuscator-LLVM是不是就是把c/c++写的代码编译成 dll, so, dylib后缀的各个平台的动态库？ 这样直接在 flutter里用 ffi调用这个动态库文件里的方法就行了？

**Comment by BruceWind** [comment]
是的，Obfuscator-LLVM 不是 必要的，它用来保证so不被 反编译。但是并不能保证别人拿你的so去继续调用，做签名校验是防止别人拷贝走了so去直接用。

**Comment by BruceWind** [comment]
> > 我当前有混编 libsodium啊，老哥。
> > 该项目不面向 windows，mac。只面向android，如果你只在Android里面调，用flutter call Java就行了，没必要那么麻烦。
> > ios你可能需要再从头来 想办法混编libsodium。
> 
> 看了一些资料，那个Obfuscator-LLVM是不是就是把c/c++写的代码编译成 dll, so, dylib后缀的各个平台的动态库？ 这样直接在 flutter里用 ffi调用这个动态库文件里的方法就行了？

Obfuscator-LLVM 是个编译环境插件。

**Comment by BruceWind** [comment]
I'm going to close this issue due to the fact that it is not a bug and no more replies.
