### ISSUE TITLE
为什么要屏蔽模拟器呢？

### ISSUE THREAD

**Issue by iostyle** [BruceWind/AESJniEncrypt#42]
为什么要屏蔽模拟器呢？如果想让模拟器可以运行的话，需要怎样配置

**Comment by BruceWind** [comment]
question1: why does you block emulator?
answer: I think hack like to use emulator.
question2: how to remove this feature?
answer:    https://github.com/BruceWind/AESJniEncrypt/blob/master/aesjni/src/main/jni/JNIEncrypt.c#L74
delete **check_is_emulator**.
```
 if (check_signature(env, instance, context) != 1 || check_is_emulator(env) != 1) {
```

**Comment by BruceWind** [comment]
I think every questions I have replied. 
If there is no more questions, I'm going to close this issue. 
Thanks.

**Comment by iostyle** [comment]
Thank you
