### ISSUE TITLE
Can you tell me which NDK version I should use? Thanks.

### ISSUE THREAD

**Issue by LandChanning** [BruceWind/AESJniEncrypt#45]
@BruceWind 你好，

我在项目的 Readme 中看到，ndk 版本要用 11-r13 的
![image](https://user-images.githubusercontent.com/8448947/145175402-d639a09e-017e-4fe7-889c-f3c410633eed.png)

但我又在 test_in_executing.sh 脚本中看到 r13 太老的提醒
![image](https://user-images.githubusercontent.com/8448947/145175232-7b8e2e46-5eb6-44d9-b0c5-43699540ee8f.png)

请问当前 master 分支下的的代码，
1、build_libsodium_for_all_android_abi.sh 脚本
2、test_in_executing.sh 脚本
3、完整 so 库编译
具体用哪个 ndk 版本编译最稳定啊？
是用一个版本，还是分开用不同版本呢？

**Comment by BruceWind** [comment]
看代码，代码基本是编译通过的。 中文read me 可能更新延迟

Land Channing ***@***.***>于2021年12月8日 周三16:39写道：

**Comment by LandChanning** [comment]
就是说两个脚本和 so 库编译，在 mac 下都可以用 r22 版 ndk 对吗

**Comment by BruceWind** [comment]
对，我有对多个NDK版本做编译测试。 
如果我只测试一个版本，当你们需要尝试其他版本时，可能会需要错误，我只是提前把一些坑踩了。其实意义不大，你们自己去踩坑自己去做修改并通过编译，难度也不大的。

**Comment by LandChanning** [comment]
好的，多谢回复
